antora:
  extensions:
    - '@springio/antora-extensions/partial-build-extension'
    - require: '@springio/antora-extensions/latest-version-extension'
    - require: '@springio/antora-extensions/inject-collector-cache-config-extension'
    - '@antora/collector-extension'
    - '@antora/atlas-extension'
    - require: '@springio/antora-extensions/root-component-extension'
      root_component_name: 'micrometer'
site:
  title: Micrometer
  url: https://docs.micrometer.io/micrometer/reference/
  robots: allow
content:
  sources:
    - url: https://github.com/micrometer-metrics/micrometer
      # Refname matching: https://docs.antora.org/antora/latest/playbook/content-refname-matching/
      branches:
        - 'main'
        - '1.1({2..9}).x' # 1.12 - 1.19
        - '1.+({2..9})+({0..9}).x' # 1.20 and above on the 1.x line
      tags:
        - 'v1.1({2..9}).+({0..9})?(-{RC,M}*)' # 1.12 - 1.19
        - 'v1.({2..9})+({0..9}).+({0..9})?(-{RC,M}*)' # 1.20 and above on the 1.x line
        - '!(v1.12.0-{RC,M}*)' # Except 1.12 milestones/rc (1.12.0 is ok)
      start_path: docs
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/micrometer
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    chomp: 'all'
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
  sourcemap: true
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: static
runtime:
  log:
    failure_level: warn
    format: pretty
ui:
  bundle:
    url: https://github.com/micrometer-metrics/antora-ui-micrometer/releases/download/latest/ui-bundle.zip
    snapshot: true 
