global:
  scrape_interval:     5s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'spring-boot-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.200.10.1:8080']
  - job_name: 'spring-boot'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['10.200.10.1:8080']
